import { ProjectData } from '@/types';

export const PROJECTS: ProjectData[] = [
  {
    id: 'riwaya',
    title: 'Riwaya',
    description: 'AI-powered storytelling platform with dynamic narrative generation.',
    tech: ['Flutter', 'Firebase', 'Gemini AI'],
    image: '/assets/proj/riwaya.png',
    featured: true,
  },
  {
    id: 'zuvo',
    title: 'Zuvo',
    description: 'Modern e-commerce mobile application with real-time inventory.',
    tech: ['Flutter', 'Supabase', 'Stripe'],
    image: '/assets/proj/zuvo.png',
    featured: true,
  },
  {
    id: 'hypercar',
    title: 'Hypercar',
    description: '3D racing game built with Flutter Flame engine.',
    tech: ['Flutter', 'Flame', 'Dart'],
    image: '/assets/proj/hypercar.png',
    featured: true,
  },
  {
    id: 'aiwrdd',
    title: 'AI WRDD',
    description: 'AI assistant with multi-model support and conversation management.',
    tech: ['Next.js', 'TypeScript', 'Gemini', 'OpenAI'],
    image: '/assets/proj/aiwrdd.png',
    featured: true,
  },
  {
    id: 'aibuddy',
    title: 'AI Buddy',
    description: 'Personal AI companion app with memory and context awareness.',
    tech: ['Flutter', 'Gemini AI', 'Hive'],
    image: '/assets/proj/aibuddy.png',
    featured: false,
  },
  {
    id: 'sapori',
    title: 'Sapori',
    description: 'Recipe discovery and meal planning application.',
    tech: ['Flutter', 'Firebase', 'GetX'],
    image: '/assets/proj/sapori.png',
    featured: false,
  },
  {
    id: 'otakuwrdd',
    title: 'Otaku WRDD',
    description: 'Anime tracking and discovery platform.',
    tech: ['Flutter', 'GraphQL', 'GetX'],
    image: '/assets/proj/otakuwrdd.png',
    featured: false,
  },
  {
    id: 'pokemonai',
    title: 'Pokemon AI',
    description: 'AI-powered Pokemon battle simulator and Pokedex.',
    tech: ['Flutter', 'Gemini AI', 'REST API'],
    image: '/assets/proj/pokemonai.png',
    featured: false,
  },
  {
    id: 'wrddgemma',
    title: 'WRDD Gemma',
    description: 'On-device AI chat powered by Google Gemma model.',
    tech: ['Flutter', 'Gemma', 'MediaPipe'],
    image: '/assets/proj/wrddgemma.png',
    featured: false,
  },
  {
    id: 'kiritowallet',
    title: 'Kirito Wallet',
    description: 'Cryptocurrency wallet with portfolio tracking.',
    tech: ['Flutter', 'CoinGecko API', 'Hive'],
    image: '/assets/proj/kiritowallet.png',
    featured: false,
  },
  {
    id: 'wrddwallet',
    title: 'WRDD Wallet',
    description: 'Personal finance and expense tracking application.',
    tech: ['Flutter', 'Firebase', 'Charts'],
    image: '/assets/proj/wrddwallet.png',
    featured: false,
  },
  {
    id: 'plainliving',
    title: 'Plain Living',
    description: 'Minimalist lifestyle and habit tracking app.',
    tech: ['Flutter', 'Supabase', 'GetX'],
    image: '/assets/proj/plainliving.png',
    featured: false,
  },
  {
    id: 'jukyomall',
    title: 'Jukyo Mall',
    description: 'E-commerce marketplace with vendor management.',
    tech: ['Flutter', 'NestJS', 'PostgreSQL'],
    image: '/assets/proj/jukyomall.png',
    featured: false,
  },
  {
    id: 'flappybird',
    title: 'Flappy Bird',
    description: 'Classic Flappy Bird clone with Flutter Flame.',
    tech: ['Flutter', 'Flame', 'Dart'],
    image: '/assets/proj/flappybird.png',
    featured: false,
  },
];
